{% set name = "sknw" %}
{% set version = "0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 905c0e55a45d96bb922fe120dacc516f29632f5d94c98273519ab9082fc2c3d9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy >=1.11
    - networkx >=1.11
    - numba >=0.29

test:
  imports:
    - sknw

about:
  home: https://github.com/yxdragon/sknw
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Analysis of object skeletons
  description: 'sknw: skeleton analysis in Python.'
  doc_url: https://github.com/yxdragon/sknw
  dev_url: https://github.com/yxdragon/sknw

extra:
  recipe-maintainers:
    - yxdragon
